version: "3"
services:
  console-service:
    container_name: tezos-fullstack-console-backend
    image: tezos-fullstack-console-backend:latest
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 30002:8080
    environment:
      TEZOS_CONSOLE_HTTP_HOST: 0.0.0.0
      TEZOS_CONSOLE_HTTP_PORT: 8080

  tezos-console-db:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_DATABASE: 'tezos_console'
      MYSQL_USER: 'tezos'
      MYSQL_PASSWORD: 'Tez0s'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/db-init:/docker-entrypoint-initdb.d
