version: "3"
services:
  console-service:
    image: scalaconsultants/tezos-fullstack-console-backend:latest
    tty: true
    stdin_open: true
    ports:
      - 30002:8080
    environment:
      TEZOS_CONSOLE_HTTP_HOST: 0.0.0.0
      TEZOS_CONSOLE_HTTP_PORT: 8080
