version: "3"
services:
  console-service:
    container_name: tezos-fullstack-console-backend-dev
    image: tezos-fullstack-console-backend-dev:latest
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 30002:8080
    environment:
      TEZOS_CONSOLE_HTTP_HOST: 0.0.0.0
      TEZOS_CONSOLE_HTTP_PORT: 8080
      TEZOS_DB_IP: ${POSTGRES_HOST}
      TEZOS_DB_NAME: ${POSTGRES_DB}
      TEZOS_DB_USERNAME: ${POSTGRES_USER}
      TEZOS_DB_PASSWORD: ${POSTGRES_PASSWORD}
